name: Deploy Documentation

# Manual trigger
# 📜 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
on:
  workflow_dispatch:
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# 📜 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build Documentation
        run: |
          xcodebuild docbuild\
            -scheme Pomodoro\
            -destination 'generic/platform=macOS'\
            -derivedDataPath ../DerivedData
      - name: Process Archive
        run: |
          mkdir _site
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting ../DerivedData/Build/Products/Debug/Pomodoro.doccarchive \
            --output-path _site \
            --hosting-base-path /pomodoro-cli/
      - name: Create Custom index.html
        run: |
          rm _site/index.html
          cat > _site/index.html <<- EOM
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url='https://dirtyhenry.github.io/pomodoro-cli/documentation/pomodoro/'" />
            </head>
           <body>
              <p>Please follow <a href="https://dirtyhenry.github.io/pomodoro-cli/documentation/pomodoro/">this link</a>.</p>
            </body>
          </html>
          EOM
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
